/**
 * The mark: two B's, cut from Fredoka itself.
 *
 * The wordmark is set in Fredoka, so a monogram merely drawn to look like it
 * always sat slightly wrong beside it. This is the same letter, mirrored, with
 * a 45-unit gap between the stems — sharing the stem instead reads as one solid
 * slab rather than as two letters.
 *
 * Generated by scripts/build-logo.py. Do not edit the path by hand; change the
 * script and re-run it so the favicon, the PWA icons, the app tile and the
 * 1000x270 lockup all move together.
 */
const D =
  'M113.5 -8.75Q77.75 -8.75 61.875 2.5Q46 13.75 42.25 32.125Q38.5 50.5 38.5 71V613Q38.5 632.75 42.375 650.5Q46.25 668.25 62.125 679.5Q78 690.75 114.5 690.75H363.5Q423 690.75 469.125 662.625Q515.25 634.5 541.875 587.625Q568.5 540.75 568.25 485.75Q568.5 464.25 563.875 442.875Q559.25 421.5 549.75 402.125Q540.25 382.75 526.25 366.5Q546.5 347 560.875 321.625Q575.25 296.25 582.625 268.25Q590 240.25 590 211Q589 164.5 572.25 124.375Q555.5 84.25 525.625 54.625Q495.75 25 456.75 8.125Q417.75 -8.75 373.5 -8.75ZM190.5 142H363.5Q381.25 142 398.625 148.625Q416 155.25 427.25 172.625Q438.5 190 438.5 222Q438.5 243.25 433.5 256.875Q428.5 270.5 419.625 278.125Q410.75 285.75 399.875 289.0Q389 292.25 377.125 293.125Q365.25 294 353.75 294H324.5Q291.25 294 276.875 308.625Q262.5 323.25 262.5 359.25Q262.5 393.5 278.125 407.5Q293.75 421.5 328.25 421.5H356.75Q367.25 421.5 378.0 422.5Q388.75 423.5 397.5 428.625Q406.25 433.75 411.75 445.125Q417.25 456.5 417.25 477.25Q417.25 511.25 400.25 525.5Q383.25 539.75 339.5 539.75H190.5Z'

export function Mark({ size = 20 }: { size?: number }) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 100 100"
      fill="currentColor"
      aria-hidden="true"
      style={{ display: 'block', flex: 'none' }}
    >
      <g transform="translate(47.068 75.969) scale(0.07616 -0.07616)">
        <path d={D} />
        <path d={D} transform="translate(77.0 0) scale(-1 1)" />
      </g>
    </svg>
  )
}
