/**
 * The mark: two B's sharing one spine.
 *
 * Drawn rather than cut from Fredoka. The glyph version was tried on 31 August
 * and reverted: real letterforms are filled, so two of them make a heavy block
 * however they are spaced, while these strokes stay open — which is what lets
 * the mark hold at 16px and sit lightly beside a wordmark that is already solid.
 *
 * Generated by scripts/build-logo.py. Do not edit by hand; change the script and
 * re-run it so the favicon, the PWA icons, the app tile and the 1000x270 lockup
 * all move together.
 */
export function Mark({ size = 20, strokeWidth }: { size?: number; strokeWidth?: number }) {
  // Small sizes need a heavier stroke or the counters close up and it greys out.
  const w = strokeWidth ?? (size <= 18 ? 10 : size <= 28 ? 9 : 8.5)
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 100 100"
      fill="none"
      stroke="currentColor"
      strokeWidth={w}
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
      style={{ display: 'block', flex: 'none' }}
    >
        <path d="M50 16v68" />
        <path d="M50 22h13a14 14 0 0 1 0 28H50" />
        <path d="M50 50h15a14 14 0 0 1 0 28H50" />
        <path d="M50 22H37a14 14 0 0 0 0 28h13" />
        <path d="M50 50H35a14 14 0 0 0 0 28h15" />
    </svg>
  )
}
